# Generated by Django 4.1.7 on 2023-10-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='suburb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, upload_to='pet_images/'),
        ),
    ]
