# Generated by Django 4.1.7 on 2023-10-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_remove_pet_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
