# Generated by Django 4.2.6 on 2023-10-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('application_manager', 'Application Manager'), ('pet_manager', 'Pet Manager')], default='user', max_length=20),
        ),
    ]
