# Generated by Django 4.1.7 on 2023-10-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_application', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='comments',
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='adopter_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='manager_comments',
            field=models.TextField(blank=True),
        ),
    ]
