# Generated by Django 4.2.6 on 2023-10-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_application', '0003_remove_adoptionapplication_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
