# Generated by Django 4.2.6 on 2023-10-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_application', '0004_adoptionapplication_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionapplication',
            old_name='adopter_comments',
            new_name='adopter_inquiries',
        ),
    ]
