# Generated by Django 4.2.6 on 2023-10-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_application', '0005_rename_adopter_comments_adoptionapplication_adopter_inquiries'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='number_of_existing_pets',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='pet_care_routine',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='residence_or_outdoor_space',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='training_and_Socialization',
            field=models.TextField(blank=True),
        ),
    ]
